export default {
  info: {
    totalrecordsperquery: 10,
    totalrecords: 239947,
    pages: 23995,
    page: 1,
    next: "https://api.harvardartmuseums.org/object?apikey=c28e4be0-4c0e-11ea-90d6-25d9a9fe80fc&page=2",
  },
  records: [
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146703,
      state: null,
      id: 372471,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509668,
          idsid: 490022938,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772760",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772760",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022938",
          height: 1718,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772760",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 35-36",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        "Untitled (note with bleed-through of previous page, left page); Untitled (view of landscape in France, right page)",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.5592079207920793,
          css3: "#dcdcdc",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.10607260726072608,
          css3: "#2f4f4f",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.0532013201320132,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.05306930693069307,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.04217821782178218,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.030693069306930693,
          css3: "#808080",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.02976897689768977,
          css3: "#2f4f4f",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.023762376237623763,
          css3: "#696969",
        },
        {
          color: "#19327d",
          spectrum: "#2474ba",
          hue: "Blue",
          percent: 0.023036303630363037,
          css3: "#191970",
        },
        {
          color: "#194baf",
          spectrum: "#1a75bb",
          hue: "Blue",
          percent: 0.01914191419141914,
          css3: "#483d8b",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2011",
      department: "Busch-Reisinger Museum",
      dateend: 2011,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372471",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.18",
      labeltext: null,
      datebegin: 2011,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372471,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372471",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146706,
      state: null,
      id: 372474,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509671,
          idsid: 490022926,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772763",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772763",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022926",
          height: 1685,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772763",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 41-42",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        'Untitled (bleed-through of previous page, left page); Untitled ("A page for Cage" with color transfer, right page)',
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.672996632996633,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.08262626262626263,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.081010101010101,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.028754208754208754,
          css3: "#a9a9a9",
        },
        {
          color: "#194b7d",
          spectrum: "#2474ba",
          hue: "Blue",
          percent: 0.02303030303030303,
          css3: "#483d8b",
        },
        {
          color: "#326496",
          spectrum: "#3973b9",
          hue: "Blue",
          percent: 0.018585858585858588,
          css3: "#483d8b",
        },
        {
          color: "#647daf",
          spectrum: "#656cb2",
          hue: "Blue",
          percent: 0.017037037037037038,
          css3: "#4682b4",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.016498316498316498,
          css3: "#696969",
        },
        {
          color: "#7d96af",
          spectrum: "#7069af",
          hue: "Blue",
          percent: 0.01589225589225589,
          css3: "#778899",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.013939393939393939,
          css3: "#2f4f4f",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2011",
      department: "Busch-Reisinger Museum",
      dateend: 2011,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372474",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.21",
      labeltext: null,
      datebegin: 2011,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372474,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372474",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146714,
      state: null,
      id: 372482,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509679,
          idsid: 490023078,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772771",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772771",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490023078",
          height: 1712,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772771",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 57-58",
      medium: "Black and red marker on paper",
      lendingpermissionlevel: 0,
      title:
        'Untitled (bleed-through of previous page, left page); Untitled (notes "for Berlin" 2014 retrospective, right page)',
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.6296,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.1264,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.10353333333333334,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.07253333333333334,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.030933333333333334,
          css3: "#808080",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.012666666666666666,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.010933333333333333,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0052,
          css3: "#2f4f4f",
        },
        {
          color: "#e19696",
          spectrum: "#e36769",
          hue: "Red",
          percent: 0.002266666666666667,
          css3: "#e9967a",
        },
        {
          color: "#191919",
          spectrum: "#1eb264",
          hue: "Grey",
          percent: 0.0016,
          css3: "#000000",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372482",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.29",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372482,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372482",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146717,
      state: null,
      id: 372485,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509682,
          idsid: 490022918,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772774",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772774",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022918",
          height: 1677,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772774",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 63-64",
      medium: "Black and red marker and blue pen on paper",
      lendingpermissionlevel: 0,
      title:
        'Untitled (bleed-through of previous page with color transfer and note, left page); Untitled (notes "for Berlin" 2014 retrospective, right page)',
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.7219727891156462,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.10231292517006803,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.08027210884353742,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.03945578231292517,
          css3: "#a9a9a9",
        },
        {
          color: "#c87d7d",
          spectrum: "#cb5781",
          hue: "Red",
          percent: 0.016122448979591836,
          css3: "#bc8f8f",
        },
        {
          color: "#c89696",
          spectrum: "#c15689",
          hue: "Red",
          percent: 0.01020408163265306,
          css3: "#bc8f8f",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.008299319727891157,
          css3: "#808080",
        },
        {
          color: "#191919",
          spectrum: "#1eb264",
          hue: "Grey",
          percent: 0.005918367346938775,
          css3: "#000000",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.0045578231292517,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0038095238095238095,
          css3: "#2f4f4f",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372485",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.32",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372485,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372485",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 0,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146719,
      state: null,
      id: 372487,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509684,
          idsid: 490022922,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772776",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772776",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022922",
          height: 1681,
        },
      ],
      worktypes: [
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
        {
          worktypeid: "128",
          worktype: "drawing",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772776",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 67-68",
      medium: "Colored marker and opaque watercolor on paper",
      lendingpermissionlevel: 0,
      title:
        "Untitled (bleed-through of previous page with color transfer, left page); Untitled (design for Neue Nationalgalerie inflatables, right page)",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.6082993197278912,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.13721088435374149,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.07918367346938776,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.05442176870748299,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.02292517006802721,
          css3: "#808080",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.021292517006802722,
          css3: "#2f4f4f",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.02095238095238095,
          css3: "#2f4f4f",
        },
        {
          color: "#64647d",
          spectrum: "#7069af",
          hue: "Blue",
          percent: 0.016394557823129253,
          css3: "#696969",
        },
        {
          color: "#191919",
          spectrum: "#1eb264",
          hue: "Grey",
          percent: 0.016258503401360543,
          css3: "#000000",
        },
        {
          color: "#e1afaf",
          spectrum: "#e36769",
          hue: "Red",
          percent: 0.00598639455782313,
          css3: "#ffb6c1",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372487",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.34",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372487,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372487",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146724,
      state: null,
      id: 372492,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509691,
          idsid: 490023054,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772783",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772783",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490023054",
          height: 1677,
        },
      ],
      worktypes: [
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
        {
          worktypeid: "128",
          worktype: "drawing",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 2,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772783",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 77-78",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        "Untitled (bleed-through of previous page, left page); Untitled (notes over bleed-through, right page)",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.8128571428571428,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.061224489795918366,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.04578231292517007,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.03653061224489796,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.01707482993197279,
          css3: "#808080",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.01272108843537415,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.009795918367346938,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.002857142857142857,
          css3: "#2f4f4f",
        },
        {
          color: "#4baf96",
          spectrum: "#33b55b",
          hue: "Green",
          percent: 0.0003401360544217687,
          css3: "#5f9ea0",
        },
        {
          color: "#4b6496",
          spectrum: "#536fb5",
          hue: "Blue",
          percent: 0.00027210884353741496,
          css3: "#483d8b",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372492",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.39",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372492,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372492",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146730,
      state: null,
      id: 372497,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509696,
          idsid: 490023138,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772788",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772788",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490023138",
          height: 1687,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772788",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 87-88",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        "Untitled (bleed-through and note, left page); Untitled (figure in landscape, right page)",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.42942760942760944,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.09952861952861952,
          css3: "#c0c0c0",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0863973063973064,
          css3: "#2f4f4f",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.06545454545454546,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.06181818181818182,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.056835016835016836,
          css3: "#808080",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.05239057239057239,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.02734006734006734,
          css3: "#2f4f4f",
        },
        {
          color: "#1964af",
          spectrum: "#1a75bb",
          hue: "Blue",
          percent: 0.02181818181818182,
          css3: "#4682b4",
        },
        {
          color: "#96afc8",
          spectrum: "#7b65ad",
          hue: "Blue",
          percent: 0.015690235690235692,
          css3: "#a9a9a9",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372497",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.44",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372497,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372497",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146731,
      state: null,
      id: 372498,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509697,
          idsid: 490022882,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772789",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772789",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022882",
          height: 1689,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772789",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 89-90",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        "Untitled (bleed-through of previous page, left page); Untitled (bleed-through and note, right page)",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.4311111111111111,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.23515151515151514,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.07885521885521886,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.07077441077441077,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.03750841750841751,
          css3: "#808080",
        },
        {
          color: "#96afc8",
          spectrum: "#7b65ad",
          hue: "Blue",
          percent: 0.028888888888888888,
          css3: "#a9a9a9",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.023097643097643096,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.021212121212121213,
          css3: "#2f4f4f",
        },
        {
          color: "#6496c8",
          spectrum: "#5b6eb4",
          hue: "Blue",
          percent: 0.014141414141414142,
          css3: "#6495ed",
        },
        {
          color: "#e16464",
          spectrum: "#e46867",
          hue: "Red",
          percent: 0.013468013468013467,
          css3: "#cd5c5c",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372498",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.45",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372498,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372498",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 0,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146732,
      state: null,
      id: 372499,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509698,
          idsid: 490022874,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772790",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772790",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022874",
          height: 1682,
        },
      ],
      worktypes: [
        {
          worktypeid: "128",
          worktype: "drawing",
        },
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772790",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 91-92",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        "Untitled (bleed-through of previous pages, left page); Untitled (Silos at Groton, MA, home, right page)",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.4210204081632653,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.11496598639455782,
          css3: "#c0c0c0",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.10775510204081633,
          css3: "#2f4f4f",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.0653061224489796,
          css3: "#a9a9a9",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.06061224489795918,
          css3: "#2f4f4f",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.055714285714285716,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.04857142857142857,
          css3: "#808080",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.04585034013605442,
          css3: "#696969",
        },
        {
          color: "#96afc8",
          spectrum: "#7b65ad",
          hue: "Blue",
          percent: 0.01850340136054422,
          css3: "#a9a9a9",
        },
        {
          color: "#4b7dc8",
          spectrum: "#4571b8",
          hue: "Blue",
          percent: 0.01183673469387755,
          css3: "#4682b4",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372499",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.46",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372499,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372499",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: "© Otto Piene Estate",
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Busch-Reisinger Museum, Gift of Elizabeth Goldring Piene",
      accesslevel: 1,
      dateoflastpageview: null,
      classificationid: 21,
      division: "Modern and Contemporary Art",
      markscount: 1,
      publicationcount: 0,
      totaluniquepageviews: 0,
      contact: "am_moderncontemporary@harvard.edu",
      colorcount: 10,
      rank: 146734,
      state: null,
      id: 372501,
      verificationleveldescription:
        "Unchecked. Object information has not been verified for completeness and has not been vetted",
      period: null,
      images: [
        {
          date: "2020-11-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 509700,
          idsid: 490022910,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop 22.0 (Macintosh);",
          renditionnumber: "772792",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772792",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/490022910",
          height: 1683,
        },
      ],
      worktypes: [
        {
          worktypeid: "337",
          worktype: "sketchbook page",
        },
        {
          worktypeid: "128",
          worktype: "drawing",
        },
      ],
      imagecount: 1,
      totalpageviews: 0,
      accessionyear: 2019,
      standardreferencenumber: null,
      signed: null,
      classification: "Drawings",
      relatedcount: 1,
      verificationlevel: 0,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:772792",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:37:52-0400",
      commentary: null,
      periodid: null,
      technique: null,
      edition: null,
      description: "Pages 95-96",
      medium: "Colored marker on paper",
      lendingpermissionlevel: 0,
      title:
        'Untitled (bleed-through of previous page, left page); Untitled ("Night-blooming cereus" in Groton, MA, right page)',
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.5718518518518518,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.19063973063973064,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.07494949494949495,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.058316498316498315,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.03259259259259259,
          css3: "#808080",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.026195286195286195,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.018383838383838384,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.011313131313131313,
          css3: "#2f4f4f",
        },
        {
          color: "#96afc8",
          spectrum: "#7b65ad",
          hue: "Blue",
          percent: 0.007676767676767677,
          css3: "#a9a9a9",
        },
        {
          color: "#7daf96",
          spectrum: "#7069af",
          hue: "Green",
          percent: 0.0034343434343434343,
          css3: "#8fbc8f",
        },
      ],
      provenance:
        "Elizabeth Goldring Piene, gift; to the Busch-Reisinger Museum, 2018.",
      groupcount: 0,
      dated: "2012",
      department: "Busch-Reisinger Museum",
      dateend: 2012,
      people: [
        {
          role: "Artist",
          birthplace: "Laasphe, Westphalia, Germany",
          gender: "male",
          displaydate: "1928 - 2014",
          prefix: null,
          culture: "German",
          displayname: "Otto Piene",
          alphasort: "Piene, Otto",
          name: "Otto Piene",
          personid: 28069,
          deathplace: "Berlin, Germany",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/372501",
      dateoffirstpageview: null,
      century: null,
      objectnumber: "2019.68.48",
      labeltext: null,
      datebegin: 2012,
      culture: null,
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 372501,
      techniqueid: null,
      dimensions: "open (approx.): 35.6 × 55.9 cm (14 × 22 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/372501",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
  ],
};
