export default {
  info: {
    totalrecordsperquery: 10,
    totalrecords: 632,
    pages: 64,
    page: 1,
    next: "https://api.harvardartmuseums.org/object?classification=Prints&apikey=c28e4be0-4c0e-11ea-90d6-25d9a9fe80fc&sort=rank&sortorder=desc&hasImage=1&q=accesslevel%3A1%20AND%20verificationlevel%3A4&page=2",
  },
  records: [
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Gift of Belinda L. Randall from the collection of John Witt Randall",
      accesslevel: 1,
      dateoflastpageview: "2021-10-28",
      classificationid: 23,
      division: "European and American Art",
      markscount: 7,
      publicationcount: 0,
      totaluniquepageviews: 18,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 8,
      rank: 251492,
      state: "ii/iii",
      id: 248659,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2006-02-10",
          copyright: "President and Fellows of Harvard College",
          imageid: 70282,
          idsid: 18816820,
          format: "image/jpeg",
          description: null,
          technique: null,
          renditionnumber: "INV034167",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV034167_dynmc",
          alttext: null,
          width: 711,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/18816820",
          height: 1024,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 19,
      accessionyear: null,
      standardreferencenumber: "Goodwin 136; John Chaloner Smith 62",
      signed: null,
      classification: "Prints",
      relatedcount: 0,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV034167_dynmc",
      titlescount: 1,
      peoplecount: 2,
      style: null,
      lastupdate: "2022-06-14T05:34:29-0400",
      commentary: null,
      periodid: null,
      technique: "Mezzotint",
      edition: null,
      description: null,
      medium: null,
      lendingpermissionlevel: 0,
      title: "Charles Erskine",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#191919",
          spectrum: "#1eb264",
          hue: "Grey",
          percent: 0.7100641025641026,
          css3: "#000000",
        },
        {
          color: "#c8c8af",
          spectrum: "#b55592",
          hue: "Green",
          percent: 0.12519230769230769,
          css3: "#c0c0c0",
        },
        {
          color: "#c8af96",
          spectrum: "#e66c64",
          hue: "Brown",
          percent: 0.06173076923076923,
          css3: "#d2b48c",
        },
        {
          color: "#e1c8c8",
          spectrum: "#c15689",
          hue: "Orange",
          percent: 0.04141025641025641,
          css3: "#d8bfd8",
        },
        {
          color: "#af967d",
          spectrum: "#c25687",
          hue: "Brown",
          percent: 0.021346153846153845,
          css3: "#bc8f8f",
        },
        {
          color: "#4b3232",
          spectrum: "#4ab851",
          hue: "Red",
          percent: 0.01942307692307692,
          css3: "#2f4f4f",
        },
        {
          color: "#967d64",
          spectrum: "#b65590",
          hue: "Brown",
          percent: 0.01173076923076923,
          css3: "#808080",
        },
        {
          color: "#7d644b",
          spectrum: "#b25593",
          hue: "Yellow",
          percent: 0.009102564102564102,
          css3: "#696969",
        },
      ],
      provenance:
        "John Witt Randall, bequest; to Belinda Lull Randall, his sister, gift; to Harvard University, 1892\r\n",
      groupcount: 0,
      dated: "1737",
      department: "Department of Prints",
      dateend: 1737,
      people: [
        {
          role: "Artist",
          birthplace: null,
          gender: "male",
          displaydate: "c. 1729 - 1765",
          prefix: null,
          culture: "British",
          displayname: "James McArdell",
          alphasort: "McArdell, James",
          name: "James McArdell",
          personid: 32221,
          deathplace: null,
          displayorder: 1,
        },
        {
          role: "Artist after",
          birthplace: "Devon, England",
          gender: "unknown",
          displaydate: "1701 - 1779",
          prefix: "After",
          culture: "British",
          displayname: "After Thomas Hudson",
          alphasort: "Hudson, Thomas",
          name: "Thomas Hudson",
          personid: 26649,
          deathplace: "Twickenham, England",
          displayorder: 2,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/248659",
      dateoffirstpageview: "2012-11-27",
      century: "18th century",
      objectnumber: "R1879",
      labeltext: null,
      datebegin: 1737,
      culture: "British",
      exhibitioncount: 1,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 248659,
      techniqueid: 260,
      dimensions:
        "plate: 32.8 × 22.5 cm (12 15/16 × 8 7/8 in.)\r\nsheet: 33.5 × 23.2 cm (13 3/16 × 9 1/8 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/248659",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Gift of Belinda L. Randall from the collection of John Witt Randall",
      accesslevel: 1,
      dateoflastpageview: "2022-05-27",
      classificationid: 23,
      division: "European and American Art",
      markscount: 0,
      publicationcount: 1,
      totaluniquepageviews: 218,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 7,
      rank: 250920,
      state: null,
      id: 213068,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2009-04-01",
          copyright: "President and Fellows of Harvard College",
          imageid: 338705,
          idsid: 12729397,
          format: "image/jpeg",
          description: null,
          technique: null,
          renditionnumber: "INV208057",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV208057_dynmc",
          alttext: null,
          width: 1024,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/12729397",
          height: 858,
        },
        {
          date: "2009-04-01",
          copyright: "President and Fellows of Harvard College",
          imageid: 338704,
          idsid: 12729396,
          format: "image/jpeg",
          description: null,
          technique: null,
          renditionnumber: "INV208056",
          displayorder: 2,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV208056_dynmc",
          alttext: null,
          width: 871,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/12729396",
          height: 1024,
        },
      ],
      worktypes: [
        {
          worktypeid: "44",
          worktype: "book",
        },
      ],
      imagecount: 2,
      totalpageviews: 274,
      accessionyear: 1998,
      standardreferencenumber: null,
      signed: null,
      classification: "Prints",
      relatedcount: 0,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV208057_dynmc",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:33:26-0400",
      commentary: null,
      periodid: null,
      technique: "Wood engraving",
      edition: "Volksausgabe",
      description: null,
      medium: null,
      lendingpermissionlevel: 0,
      title: "The Bible in Pictures",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#e1c8c8",
          spectrum: "#c15689",
          hue: "Orange",
          percent: 0.3456,
          css3: "#d8bfd8",
        },
        {
          color: "#c8c8af",
          spectrum: "#b55592",
          hue: "Green",
          percent: 0.23477333333333333,
          css3: "#c0c0c0",
        },
        {
          color: "#afaf96",
          spectrum: "#8e5ea7",
          hue: "Green",
          percent: 0.15402666666666667,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d64",
          spectrum: "#6cbd45",
          hue: "Yellow",
          percent: 0.11242666666666666,
          css3: "#808080",
        },
        {
          color: "#96967d",
          spectrum: "#8e5ea7",
          hue: "Green",
          percent: 0.09930666666666667,
          css3: "#808080",
        },
        {
          color: "#64644b",
          spectrum: "#59ba4a",
          hue: "Green",
          percent: 0.04821333333333333,
          css3: "#696969",
        },
        {
          color: "#4b4b32",
          spectrum: "#4ab851",
          hue: "Green",
          percent: 0.005653333333333333,
          css3: "#556b2f",
        },
      ],
      provenance: null,
      groupcount: 0,
      dated: "1858",
      department: "Department of Prints",
      dateend: 1858,
      people: [
        {
          role: "Artist",
          birthplace: null,
          gender: "unknown",
          displaydate: "1794 - 1872",
          prefix: "After",
          culture: "German",
          displayname: "After Julius Schnorr von Carolsfeld",
          alphasort: "Schnorr von Carolsfeld, Julius",
          name: "Julius Schnorr von Carolsfeld",
          personid: 28546,
          deathplace: null,
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/213068",
      dateoffirstpageview: "2009-06-15",
      century: "19th century",
      objectnumber: "R1165NA",
      labeltext: null,
      datebegin: 1858,
      culture: "German",
      exhibitioncount: 1,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 213068,
      techniqueid: 525,
      dimensions: "sheet: 29.2 x 35.2 cm (11 1/2 x 13 7/8 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/213068",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Acquisition Fund for Prints",
      accesslevel: 1,
      dateoflastpageview: "2022-04-24",
      classificationid: 23,
      division: "European and American Art",
      markscount: 13,
      publicationcount: 1,
      totaluniquepageviews: 71,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 8,
      rank: 235716,
      state: "only state",
      id: 4859,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2017-07-19",
          copyright: "President and Fellows of Harvard College",
          imageid: 477547,
          idsid: 433893072,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop CS6 (Macintosh);",
          renditionnumber: "764241",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764241",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/433893072",
          height: 1848,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 86,
      accessionyear: 2005,
      standardreferencenumber: "Delteil 38; Clément 30; Brugerolles E.28",
      signed: null,
      classification: "Prints",
      relatedcount: 2,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764241",
      titlescount: 2,
      peoplecount: 3,
      style: null,
      lastupdate: "2022-06-14T05:29:09-0400",
      commentary: null,
      periodid: null,
      technique: "Lithograph",
      edition: null,
      description: null,
      medium: "Lithograph on off-white wove paper",
      lendingpermissionlevel: 0,
      title: "A Paraleytic Woman",
      accessionmethod: "Purchase",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.6415432098765432,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.16067901234567902,
          css3: "#c0c0c0",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.0878395061728395,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.05617283950617284,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.03166666666666667,
          css3: "#808080",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.015246913580246914,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.006358024691358025,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0004938271604938272,
          css3: "#2f4f4f",
        },
      ],
      provenance:
        "Eugene Delacroix. Alexis Hubert Rouart (Lugt 2187a), Paris. [Paul Prouté, S.A., Paris], sold; to Harvard Art Museums, 2005",
      groupcount: 0,
      dated: "April 1, 1821",
      department: "Department of Prints",
      dateend: 1821,
      people: [
        {
          role: "Artist",
          birthplace: "Rouen",
          gender: "male",
          displaydate: "1791 - 1824",
          prefix: null,
          culture: "French",
          displayname: "Théodore Géricault",
          alphasort: "Géricault, Théodore",
          name: "Théodore Géricault",
          personid: 21958,
          deathplace: "Paris",
          displayorder: 1,
        },
        {
          role: "Printer",
          birthplace: "London",
          gender: "male",
          displaydate: "1789 - 1850",
          prefix: "Printed by",
          culture: "British",
          displayname: "Printed by Charles Joseph Hullmandel",
          alphasort: "Hullmandel, Charles Joseph",
          name: "Charles Joseph Hullmandel",
          personid: 62231,
          deathplace: "London",
          displayorder: 2,
        },
        {
          role: "Publisher",
          birthplace: null,
          gender: "unknown",
          displaydate: "active 1819 - 1935",
          prefix: "Published by",
          culture: "British",
          displayname: "Published by Rodwell & Martin",
          alphasort: "Rodwell & Martin",
          name: "Rodwell & Martin",
          personid: 64690,
          deathplace: null,
          displayorder: 3,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/4859",
      dateoffirstpageview: "2009-08-12",
      century: "19th century",
      objectnumber: "M26553",
      labeltext: null,
      datebegin: 1821,
      culture: "French",
      exhibitioncount: 1,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 4859,
      techniqueid: 136,
      dimensions:
        "image: 22.3 x 31.7 cm (8 3/4 x 12 1/2 in.)\r\nsheet: 35.7 × 49.1 cm (14 1/16 × 19 5/16 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/4859",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Gift of Marjorie B. and Martin Cohn in honor of Emily Rauh Pulitzer",
      accesslevel: 1,
      dateoflastpageview: "2022-06-05",
      classificationid: 23,
      division: "European and American Art",
      markscount: 1,
      publicationcount: 3,
      totaluniquepageviews: 119,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 9,
      rank: 235216,
      state: "v/xxii",
      id: 235740,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2005-01-03",
          copyright: "President and Fellows of Harvard College",
          imageid: 134468,
          idsid: 17916305,
          format: "image/jpeg",
          description:
            "A network of finely drawn and scratched lines depicts a woman with her back to the viewer as she steps out of a washtub. With her right foot planted on the floor, she leans forward, holding the edge of the tub with both hands as she pulls her other leg out. We see her dark hair but her face is obscured by her shoulder. To the right, another figure stands, completely obscured by a towel she holds ready, only her dark hair and maid’s bonnet being visible. Cushioned furniture and a counter with two large empty vases crowd the small room.",
          technique: null,
          renditionnumber: "76822",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:76822_dynmc",
          alttext:
            "A nude woman stepping out of a bathtub as another figure holds up a towel",
          width: 1014,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/17916305",
          height: 1024,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 139,
      accessionyear: 2005,
      standardreferencenumber: "Del. 39, Adh. 49, R.-S. 42",
      signed: null,
      classification: "Prints",
      relatedcount: 0,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:76822_dynmc",
      titlescount: 2,
      peoplecount: 1,
      style: null,
      lastupdate: "2022-06-14T05:34:06-0400",
      commentary: null,
      periodid: null,
      technique: "Drypoint and aquatint",
      edition: null,
      description: null,
      medium: null,
      lendingpermissionlevel: 0,
      title: "Leaving the Bath",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#c8c8af",
          spectrum: "#b55592",
          hue: "Green",
          percent: 0.17977477477477477,
          css3: "#c0c0c0",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.17702702702702702,
          css3: "#696969",
        },
        {
          color: "#afaf96",
          spectrum: "#8e5ea7",
          hue: "Green",
          percent: 0.16234234234234235,
          css3: "#a9a9a9",
        },
        {
          color: "#96967d",
          spectrum: "#8e5ea7",
          hue: "Green",
          percent: 0.13063063063063063,
          css3: "#808080",
        },
        {
          color: "#7d7d64",
          spectrum: "#6cbd45",
          hue: "Yellow",
          percent: 0.12072072072072072,
          css3: "#808080",
        },
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.11382882882882883,
          css3: "#dcdcdc",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.09959459459459459,
          css3: "#2f4f4f",
        },
        {
          color: "#fafae1",
          spectrum: "#ed765a",
          hue: "Green",
          percent: 0.015810810810810812,
          css3: "#ffffe0",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0002702702702702703,
          css3: "#2f4f4f",
        },
      ],
      provenance:
        'Alexis Rouart (Lugt 2187a), sold [through Estampes de Gericault, Delacroix, Manet, Degas provenant de la collection Alexis H. Rouart, Galerie Marcel Guiot, no. 184 (as "La presente epreuve est la seule mentionee par Delteil. Rarissime sino unique.", 1933)]. [Robert M. Light & Co., Santa Barbara], sold; to Mariot F. Hughes, Boston, MA, sold; to Ruth B. Benedict, Washington, D.C., exchanged; with Marjorie B. Cohn for Rembrandt, "Christ Carried to the Tomb," 1985, gift; to Harvard Art Museums.',
      groupcount: 0,
      dated: "1879-1880",
      department: "Department of Prints",
      dateend: 1880,
      people: [
        {
          role: "Artist",
          birthplace: "Paris, France",
          gender: "male",
          displaydate: "1834 - 1917",
          prefix: null,
          culture: "French",
          displayname: "Hilaire-Germain-Edgar Degas",
          alphasort: "Degas, Hilaire-Germain-Edgar",
          name: "Hilaire-Germain-Edgar Degas",
          personid: 35055,
          deathplace: "Paris, France",
          displayorder: 1,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/235740",
      dateoffirstpageview: "2009-10-25",
      century: "19th century",
      objectnumber: "M26274",
      labeltext: null,
      datebegin: 1879,
      culture: "French",
      exhibitioncount: 3,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 235740,
      techniqueid: 2415,
      dimensions: "plate: 12.7 x 12.7 cm (5 x 5 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/235740",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Purchase through the generosity of Melvin R. Seiden",
      accesslevel: 1,
      dateoflastpageview: "2022-03-29",
      classificationid: 23,
      division: "European and American Art",
      markscount: 5,
      publicationcount: 0,
      totaluniquepageviews: 28,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 7,
      rank: 230652,
      state: null,
      id: 253688,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2019-07-01",
          copyright: "President and Fellows of Harvard College",
          imageid: 501061,
          idsid: 472352517,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop CC 2018 (Macintosh);",
          renditionnumber: "770574",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:770574",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/472352517",
          height: 1769,
        },
        {
          date: "2007-07-13",
          copyright: "President and Fellows of Harvard College",
          imageid: 254579,
          idsid: 20410140,
          format: "image/jpeg",
          description: null,
          technique: null,
          renditionnumber: "INV153467",
          displayorder: 2,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV153467_dynmc",
          alttext: null,
          width: 1024,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/20410140",
          height: 702,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 2,
      totalpageviews: 35,
      accessionyear: 1996,
      standardreferencenumber: null,
      signed: null,
      classification: "Prints",
      relatedcount: 0,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:770574",
      titlescount: 2,
      peoplecount: 2,
      style: null,
      lastupdate: "2022-06-14T05:34:38-0400",
      commentary: null,
      periodid: null,
      technique: "Wood engraving",
      edition: null,
      description: null,
      medium: "Wood engraving and letterpress on off-white laid paper",
      lendingpermissionlevel: 0,
      title: "Compromise with the South",
      accessionmethod: "Purchase",
      colors: [
        {
          color: "#c8c8af",
          spectrum: "#b55592",
          hue: "Green",
          percent: 0.25461538461538463,
          css3: "#c0c0c0",
        },
        {
          color: "#c8af96",
          spectrum: "#e66c64",
          hue: "Brown",
          percent: 0.1691025641025641,
          css3: "#d2b48c",
        },
        {
          color: "#7d7d64",
          spectrum: "#6cbd45",
          hue: "Yellow",
          percent: 0.15224358974358973,
          css3: "#808080",
        },
        {
          color: "#96967d",
          spectrum: "#8e5ea7",
          hue: "Green",
          percent: 0.1408974358974359,
          css3: "#808080",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.13967948717948717,
          css3: "#2f4f4f",
        },
        {
          color: "#64644b",
          spectrum: "#59ba4a",
          hue: "Green",
          percent: 0.11115384615384616,
          css3: "#696969",
        },
        {
          color: "#e1e1c8",
          spectrum: "#e9715f",
          hue: "Green",
          percent: 0.03230769230769231,
          css3: "#dcdcdc",
        },
      ],
      provenance: "[Second Story Books], sold; to the Harvard Art Museums,1996",
      groupcount: 0,
      dated: "1864",
      department: "Department of Prints",
      dateend: 1864,
      people: [
        {
          role: "Artist",
          birthplace: null,
          gender: "unknown",
          displaydate: null,
          prefix: null,
          culture: null,
          displayname: "Unidentified Artist",
          alphasort: "Unidentified Artist",
          name: "Unidentified Artist",
          personid: 34147,
          deathplace: null,
          displayorder: 1,
        },
        {
          role: "Artist after",
          birthplace: "Landau, Bavaria",
          gender: "male",
          displaydate: "1840 - 1902",
          prefix: "After",
          culture: "American",
          displayname: "After Thomas Nast",
          alphasort: "Nast, Thomas",
          name: "Thomas Nast",
          personid: 18465,
          deathplace: "Guayaquil, Ecuador",
          displayorder: 2,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/253688",
      dateoffirstpageview: "2009-10-27",
      century: "19th century",
      objectnumber: "M23239",
      labeltext: null,
      datebegin: 1864,
      culture: "American",
      exhibitioncount: 0,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 253688,
      techniqueid: 525,
      dimensions:
        "block: 23.5 × 35.4 cm (9 1/4 × 13 15/16 in.)\r\nsheet: 28.1 × 40.6 cm (11 1/16 × 16 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/253688",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Gift of James Goodfriend in memory of Milton J. Goodfriend, M. D.",
      accesslevel: 1,
      dateoflastpageview: "2021-12-02",
      classificationid: 23,
      division: "European and American Art",
      markscount: 5,
      publicationcount: 0,
      totaluniquepageviews: 15,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 8,
      rank: 227069,
      state: "i/iv",
      id: 260688,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2008-06-16",
          copyright: "President and Fellows of Harvard College",
          imageid: 312576,
          idsid: 20460535,
          format: "image/jpeg",
          description: null,
          technique: null,
          renditionnumber: "INV195978",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV195978_dynmc",
          alttext: null,
          width: 726,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/20460535",
          height: 1024,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 16,
      accessionyear: 1989,
      standardreferencenumber: "John Chaloner Smith 53",
      signed: null,
      classification: "Prints",
      relatedcount: 1,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV195978_dynmc",
      titlescount: 1,
      peoplecount: 2,
      style: null,
      lastupdate: "2022-06-14T05:34:51-0400",
      commentary: null,
      periodid: null,
      technique: "Mezzotint",
      edition: null,
      description: null,
      medium: null,
      lendingpermissionlevel: 0,
      title: "Miss Anne Day, afterwards Lady Fehoulet",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#191919",
          spectrum: "#1eb264",
          hue: "Grey",
          percent: 0.46540880503144655,
          css3: "#000000",
        },
        {
          color: "#e1c8af",
          spectrum: "#e9715f",
          hue: "Orange",
          percent: 0.16628930817610063,
          css3: "#f5deb3",
        },
        {
          color: "#644b32",
          spectrum: "#59ba4a",
          hue: "Brown",
          percent: 0.09742138364779875,
          css3: "#556b2f",
        },
        {
          color: "#c8af96",
          spectrum: "#e66c64",
          hue: "Brown",
          percent: 0.06006289308176101,
          css3: "#d2b48c",
        },
        {
          color: "#e1e1c8",
          spectrum: "#e9715f",
          hue: "Green",
          percent: 0.057169811320754715,
          css3: "#dcdcdc",
        },
        {
          color: "#7d644b",
          spectrum: "#b25593",
          hue: "Yellow",
          percent: 0.05440251572327044,
          css3: "#696969",
        },
        {
          color: "#967d64",
          spectrum: "#b65590",
          hue: "Brown",
          percent: 0.050125786163522014,
          css3: "#808080",
        },
        {
          color: "#af967d",
          spectrum: "#c25687",
          hue: "Brown",
          percent: 0.04911949685534591,
          css3: "#bc8f8f",
        },
      ],
      provenance: "James Goodfriend, gift; to Fogg Art Museum, 1989",
      groupcount: 0,
      dated: "1760",
      department: "Department of Prints",
      dateend: 1760,
      people: [
        {
          role: "Artist",
          birthplace: null,
          gender: "male",
          displaydate: "c. 1729 - 1765",
          prefix: null,
          culture: "British",
          displayname: "James McArdell",
          alphasort: "McArdell, James",
          name: "James McArdell",
          personid: 32221,
          deathplace: null,
          displayorder: 1,
        },
        {
          role: "Artist after",
          birthplace: "Plympton, England",
          gender: "male",
          displaydate: "1723 - 1792",
          prefix: "After",
          culture: "British",
          displayname: "After Sir Joshua Reynolds",
          alphasort: "Reynolds, Joshua Sir",
          name: "Sir Joshua Reynolds",
          personid: 28265,
          deathplace: "London, England",
          displayorder: 2,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/260688",
      dateoffirstpageview: "2016-03-15",
      century: "18th century",
      objectnumber: "M21016",
      labeltext: null,
      datebegin: 1760,
      culture: "British",
      exhibitioncount: 1,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 260688,
      techniqueid: 260,
      dimensions:
        "plate: 32.5 × 22.5 cm (12 13/16 × 8 7/8 in.)\r\nsheet: 33.1 × 23 cm (13 1/16 × 9 1/16 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/260688",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline: "Harvard Art Museums/Fogg Museum, Deknatel Purchase Fund",
      accesslevel: 1,
      dateoflastpageview: "2021-10-06",
      classificationid: 23,
      division: "European and American Art",
      markscount: 4,
      publicationcount: 0,
      totaluniquepageviews: 32,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 8,
      rank: 221694,
      state: "ii/iv",
      id: 265666,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2017-07-19",
          copyright: "President and Fellows of Harvard College",
          imageid: 477567,
          idsid: 433893152,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop CS6 (Macintosh);",
          renditionnumber: "764261",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764261",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/433893152",
          height: 1929,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 38,
      accessionyear: null,
      standardreferencenumber: "Delteil 56; Clément 57; Brugerolles E.54",
      signed: null,
      classification: "Prints",
      relatedcount: 12,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764261",
      titlescount: 3,
      peoplecount: 3,
      style: null,
      lastupdate: "2022-06-14T05:35:00-0400",
      commentary: null,
      periodid: null,
      technique: "Lithograph",
      edition: null,
      description: null,
      medium: "Lithograph on chine collé",
      lendingpermissionlevel: 0,
      title: "Arab Horse",
      accessionmethod: "Purchase",
      colors: [
        {
          color: "#e1e1c8",
          spectrum: "#e9715f",
          hue: "Green",
          percent: 0.7200589970501475,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8af",
          spectrum: "#b55592",
          hue: "Green",
          percent: 0.07498525073746312,
          css3: "#c0c0c0",
        },
        {
          color: "#afaf96",
          spectrum: "#8e5ea7",
          hue: "Green",
          percent: 0.0552212389380531,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.047315634218289084,
          css3: "#a9a9a9",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.0391740412979351,
          css3: "#696969",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.03463126843657817,
          css3: "#808080",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.024837758112094394,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0037758112094395282,
          css3: "#2f4f4f",
        },
      ],
      provenance: null,
      groupcount: 0,
      dated: "1822",
      department: "Department of Prints",
      dateend: 1822,
      people: [
        {
          role: "Artist",
          birthplace: "Rouen",
          gender: "male",
          displaydate: "1791 - 1824",
          prefix: null,
          culture: "French",
          displayname: "Théodore Géricault",
          alphasort: "Géricault, Théodore",
          name: "Théodore Géricault",
          personid: 21958,
          deathplace: "Paris",
          displayorder: 1,
        },
        {
          role: "Printer",
          birthplace: "Mulhouse, France",
          gender: "male",
          displaydate: "1788-1839",
          prefix: "Printed by",
          culture: "German",
          displayname: "Printed by Gottfried Engelmann",
          alphasort: "Engelmann, Gottfried",
          name: "Gottfried Engelmann",
          personid: 33882,
          deathplace: "Mulhouse, France",
          displayorder: 2,
        },
        {
          role: "Publisher",
          birthplace: null,
          gender: "unknown",
          displaydate: "active 1815 - 1871",
          prefix: "Published by",
          culture: "French",
          displayname: "Published by Gihaut Frères",
          alphasort: "Gihaut Frères",
          name: "Gihaut Frères",
          personid: 57301,
          deathplace: null,
          displayorder: 3,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/265666",
      dateoffirstpageview: "2010-08-15",
      century: "19th century",
      objectnumber: "M15617",
      labeltext: null,
      datebegin: 1822,
      culture: "French",
      exhibitioncount: 2,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 265666,
      techniqueid: 136,
      dimensions:
        "chine collé: 20.7 × 25.9 cm (8 1/8 × 10 3/16 in.)\r\nsheet: 25.7 × 34 cm (10 1/8 × 13 3/8 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/265666",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline: "Harvard Art Museums/Fogg Museum, Deknatel Purchase Fund",
      accesslevel: 1,
      dateoflastpageview: "2022-03-01",
      classificationid: 23,
      division: "European and American Art",
      markscount: 3,
      publicationcount: 0,
      totaluniquepageviews: 52,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 8,
      rank: 221693,
      state: "ii/iv",
      id: 265628,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2017-07-19",
          copyright: "President and Fellows of Harvard College",
          imageid: 477562,
          idsid: 433893140,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop CS6 (Macintosh);",
          renditionnumber: "764256",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764256",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/433893140",
          height: 1860,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 65,
      accessionyear: null,
      standardreferencenumber: "Delteil 55; Clément 56; Brugerolles E.53",
      signed: null,
      classification: "Prints",
      relatedcount: 11,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764256",
      titlescount: 3,
      peoplecount: 3,
      style: null,
      lastupdate: "2022-06-14T05:35:00-0400",
      commentary: null,
      periodid: null,
      technique: "Lithograph",
      edition: null,
      description: null,
      medium: "Lithograph on chine collé",
      lendingpermissionlevel: 0,
      title: "Flemish Horses",
      accessionmethod: "Purchase",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.7001834862385321,
          css3: "#dcdcdc",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.07480122324159022,
          css3: "#a9a9a9",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.06048929663608563,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.04440366972477064,
          css3: "#808080",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.04195718654434251,
          css3: "#c0c0c0",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.03902140672782874,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.03529051987767584,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.003853211009174312,
          css3: "#2f4f4f",
        },
      ],
      provenance: null,
      groupcount: 0,
      dated: "1822",
      department: "Department of Prints",
      dateend: 1822,
      people: [
        {
          role: "Artist",
          birthplace: "Rouen",
          gender: "male",
          displaydate: "1791 - 1824",
          prefix: null,
          culture: "French",
          displayname: "Théodore Géricault",
          alphasort: "Géricault, Théodore",
          name: "Théodore Géricault",
          personid: 21958,
          deathplace: "Paris",
          displayorder: 1,
        },
        {
          role: "Printer",
          birthplace: "Mulhouse, France",
          gender: "male",
          displaydate: "1788-1839",
          prefix: "Printed by",
          culture: "German",
          displayname: "Printed by Gottfried Engelmann",
          alphasort: "Engelmann, Gottfried",
          name: "Gottfried Engelmann",
          personid: 33882,
          deathplace: "Mulhouse, France",
          displayorder: 2,
        },
        {
          role: "Publisher",
          birthplace: null,
          gender: "unknown",
          displaydate: "active 1815 - 1871",
          prefix: "Published by",
          culture: "French",
          displayname: "Published by Gihaut Frères",
          alphasort: "Gihaut Frères",
          name: "Gihaut Frères",
          personid: 57301,
          deathplace: null,
          displayorder: 3,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/265628",
      dateoffirstpageview: "2010-02-17",
      century: "19th century",
      objectnumber: "M15616",
      labeltext: null,
      datebegin: 1822,
      culture: "French",
      exhibitioncount: 2,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 265628,
      techniqueid: 136,
      dimensions:
        "chine collé: 21.5 × 25.5 cm (8 7/16 × 10 1/16 in.)\r\nsheet: 25.3 × 34.6 cm (9 15/16 × 13 5/8 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/265628",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline: "Harvard Art Museums/Fogg Museum, Deknatel Purchase Fund",
      accesslevel: 1,
      dateoflastpageview: "2022-04-04",
      classificationid: 23,
      division: "European and American Art",
      markscount: 4,
      publicationcount: 0,
      totaluniquepageviews: 24,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 8,
      rank: 221687,
      state: "ii/iv",
      id: 265748,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2017-07-19",
          copyright: "President and Fellows of Harvard College",
          imageid: 477569,
          idsid: 433893164,
          format: "image/jpeg",
          description: null,
          technique:
            "Make:Hasselblad;Model:Hasselblad H5D-50c MS;Orientation:1;Software:Adobe Photoshop CS6 (Macintosh);",
          renditionnumber: "764263",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764263",
          alttext: null,
          width: 2550,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/433893164",
          height: 1900,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 24,
      accessionyear: null,
      standardreferencenumber: "Delteil 49; Clément 50; Brugerolles E.47",
      signed: null,
      classification: "Prints",
      relatedcount: 11,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:764263",
      titlescount: 3,
      peoplecount: 3,
      style: null,
      lastupdate: "2022-06-14T05:35:00-0400",
      commentary: null,
      periodid: null,
      technique: "Lithograph",
      edition: null,
      description: null,
      medium: "Lithograph on chine collé",
      lendingpermissionlevel: 0,
      title: "Caux Horse",
      accessionmethod: "Purchase",
      colors: [
        {
          color: "#e1e1e1",
          spectrum: "#955ba5",
          hue: "Grey",
          percent: 0.7161561561561561,
          css3: "#dcdcdc",
        },
        {
          color: "#c8c8c8",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.06252252252252252,
          css3: "#c0c0c0",
        },
        {
          color: "#969696",
          spectrum: "#8761aa",
          hue: "Grey",
          percent: 0.05921921921921922,
          css3: "#a9a9a9",
        },
        {
          color: "#7d7d7d",
          spectrum: "#8362aa",
          hue: "Grey",
          percent: 0.05237237237237237,
          css3: "#808080",
        },
        {
          color: "#afafaf",
          spectrum: "#8c5fa8",
          hue: "Grey",
          percent: 0.045825825825825825,
          css3: "#a9a9a9",
        },
        {
          color: "#646464",
          spectrum: "#7866ad",
          hue: "Grey",
          percent: 0.03981981981981982,
          css3: "#696969",
        },
        {
          color: "#4b4b4b",
          spectrum: "#3db657",
          hue: "Grey",
          percent: 0.02156156156156156,
          css3: "#2f4f4f",
        },
        {
          color: "#323232",
          spectrum: "#2eb45d",
          hue: "Grey",
          percent: 0.0025225225225225223,
          css3: "#2f4f4f",
        },
      ],
      provenance: null,
      groupcount: 0,
      dated: "1822",
      department: "Department of Prints",
      dateend: 1822,
      people: [
        {
          role: "Artist",
          birthplace: "Rouen",
          gender: "male",
          displaydate: "1791 - 1824",
          prefix: null,
          culture: "French",
          displayname: "Théodore Géricault",
          alphasort: "Géricault, Théodore",
          name: "Théodore Géricault",
          personid: 21958,
          deathplace: "Paris",
          displayorder: 1,
        },
        {
          role: "Printer",
          birthplace: "Mulhouse, France",
          gender: "male",
          displaydate: "1788-1839",
          prefix: "Printed by",
          culture: "German",
          displayname: "Printed by Gottfried Engelmann",
          alphasort: "Engelmann, Gottfried",
          name: "Gottfried Engelmann",
          personid: 33882,
          deathplace: "Mulhouse, France",
          displayorder: 2,
        },
        {
          role: "Publisher",
          birthplace: null,
          gender: "unknown",
          displaydate: "active 1815 - 1871",
          prefix: "Published by",
          culture: "French",
          displayname: "Published by Gihaut Frères",
          alphasort: "Gihaut Frères",
          name: "Gihaut Frères",
          personid: 57301,
          deathplace: null,
          displayorder: 3,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/265748",
      dateoffirstpageview: "2012-10-17",
      century: "19th century",
      objectnumber: "M15610",
      labeltext: null,
      datebegin: 1822,
      culture: "French",
      exhibitioncount: 1,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 265748,
      techniqueid: 136,
      dimensions:
        "chine collé: 21.4 × 25.4 cm (8 7/16 × 10 in.)\r\nsheet: 26.1 × 34.9 cm (10 1/4 × 13 3/4 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/265748",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
    {
      copyright: null,
      contextualtextcount: 0,
      creditline:
        "Harvard Art Museums/Fogg Museum, Gift of Kenneth J. Conant in memory of Georges Gaillard",
      accesslevel: 1,
      dateoflastpageview: "2022-06-08",
      classificationid: 23,
      division: "European and American Art",
      markscount: 0,
      publicationcount: 0,
      totaluniquepageviews: 14,
      contact: "am_europeanamerican@harvard.edu",
      colorcount: 6,
      rank: 220902,
      state: null,
      id: 264875,
      verificationleveldescription:
        "Best. Object is extensively researched, well described and information is vetted",
      period: null,
      images: [
        {
          date: "2006-03-10",
          copyright: "President and Fellows of Harvard College",
          imageid: 73035,
          idsid: 18826332,
          format: "image/jpeg",
          description: null,
          technique: null,
          renditionnumber: "INV038745",
          displayorder: 1,
          baseimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV038745_dynmc",
          alttext: null,
          width: 1024,
          publiccaption: null,
          iiifbaseuri: "https://ids.lib.harvard.edu/ids/iiif/18826332",
          height: 665,
        },
      ],
      worktypes: [
        {
          worktypeid: "288",
          worktype: "print",
        },
      ],
      imagecount: 1,
      totalpageviews: 16,
      accessionyear: 1970,
      standardreferencenumber: null,
      signed: null,
      classification: "Prints",
      relatedcount: 0,
      verificationlevel: 4,
      primaryimageurl: "https://nrs.harvard.edu/urn-3:HUAM:INV038745_dynmc",
      titlescount: 3,
      peoplecount: 3,
      style: null,
      lastupdate: "2022-06-14T05:34:58-0400",
      commentary: null,
      periodid: null,
      technique: "Engraving",
      edition: null,
      description: null,
      medium: null,
      lendingpermissionlevel: 0,
      title: "View of the Town of Cluny near the Levée bridge",
      accessionmethod: "Gift",
      colors: [
        {
          color: "#c8af96",
          spectrum: "#e66c64",
          hue: "Brown",
          percent: 0.526872852233677,
          css3: "#d2b48c",
        },
        {
          color: "#af967d",
          spectrum: "#c25687",
          hue: "Brown",
          percent: 0.18151202749140893,
          css3: "#bc8f8f",
        },
        {
          color: "#967d64",
          spectrum: "#b65590",
          hue: "Brown",
          percent: 0.128659793814433,
          css3: "#808080",
        },
        {
          color: "#7d644b",
          spectrum: "#b25593",
          hue: "Yellow",
          percent: 0.07560137457044673,
          css3: "#696969",
        },
        {
          color: "#644b32",
          spectrum: "#59ba4a",
          hue: "Brown",
          percent: 0.06054982817869416,
          css3: "#556b2f",
        },
        {
          color: "#323219",
          spectrum: "#3db657",
          hue: "Brown",
          percent: 0.026804123711340205,
          css3: "#2f4f4f",
        },
      ],
      provenance: "Kenneth J. Conant, gift; to Fogg Art Museum, 1970",
      groupcount: 0,
      dated: "1781",
      department: "Department of Prints",
      dateend: 1781,
      people: [
        {
          role: "Artist",
          birthplace: null,
          gender: "unknown",
          displaydate: null,
          prefix: null,
          culture: null,
          displayname: "Unidentified Artist",
          alphasort: "Unidentified Artist",
          name: "Unidentified Artist",
          personid: 34147,
          deathplace: null,
          displayorder: 1,
        },
        {
          role: "Artist",
          birthplace: null,
          gender: "male",
          displaydate: "1741 - 1811",
          prefix: "Under the direction of",
          culture: "French",
          displayname: "Under the direction of Louis Joseph Masquelier",
          alphasort: "Masquelier, Louis Joseph",
          name: "Louis Joseph Masquelier",
          personid: 32514,
          deathplace: null,
          displayorder: 2,
        },
        {
          role: "Artist after",
          birthplace: "Dijon, France",
          gender: "male",
          displaydate: "1716 - c. 1803",
          prefix: "After",
          culture: "French",
          displayname: "After Jean-Baptiste Lallemand",
          alphasort: "Lallemand, Jean-Baptiste",
          name: "Jean-Baptiste Lallemand",
          personid: 32287,
          deathplace: "Paris, France",
          displayorder: 3,
        },
      ],
      url: "https://www.harvardartmuseums.org/collections/object/264875",
      dateoffirstpageview: "2010-05-04",
      century: "18th century",
      objectnumber: "M14956",
      labeltext: null,
      datebegin: 1781,
      culture: "French",
      exhibitioncount: 1,
      imagepermissionlevel: 0,
      mediacount: 0,
      objectid: 264875,
      techniqueid: 98,
      dimensions:
        "Image: 21.2 × 35 cm (8 3/8 × 13 3/4 in.)\r\nPlate: 24.5 × 36.6 cm (9 5/8 × 14 7/16 in.)\r\nSheet: 32.5 × 50.1 cm (12 13/16 × 19 3/4 in.)",
      seeAlso: [
        {
          id: "https://iiif.harvardartmuseums.org/manifests/object/264875",
          type: "IIIF Manifest",
          format: "application/json",
          profile: "http://iiif.io/api/presentation/2/context.json",
        },
      ],
    },
  ],
};
